title: "Daily Blog"
description: "A daily blog"
timezone: "UTC"
markdown: kramdown
permalink: /:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
